sudo: required

language: go

services:
  - docker

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - go get -u github.com/kardianos/govendor
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else govendor sync; fi

script:
  - make test
  - make docker_test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt

