sudo: required

language: go

services:
  - docker

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - mast

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

script:
  - make test
  - make docker_test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt

